require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '13.0'
prepare_react_native_project!
# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),

flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'xenia' do
  $static_framework = []
  rn_maps_path = '../node_modules/react-native-maps'
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  $static_framework += [
    'react-native-maps',
    'react-native-google-maps',
    'Google-Maps-iOS-Utils',
    'GoogleMaps',
  ]

  # Pods for xenia
  # permissions_path = '../node_modules/react-native-permissions/ios'
  
  # pod 'Firebase/Core'
  # pod 'CryptoSwift'
  # pod 'FirebaseCoreInternal'
  # pod 'RNPermissions', :path =>  '../node_modules/react-native-permissions'
  # pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'
  # pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  # pod 'RNAppleHealthKit', :path => "../node_modules/react-native-health"
  # pod 'react-native-geolocation-service', path: '../node_modules/react-native-geolocation-service'
  # pod 'FBReactNativeSpec', :path => "../node_modules/react-native/React/FBReactNativeSpec"
  # pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  # pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  # pod 'React', :path => '../node_modules/react-native/'
  # pod 'React-Core', :path => '../node_modules/react-native/'
  # pod 'React-logger', :path => '../node_modules/react-native/ReactCommon/logger'
  # pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  # pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  # pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  # pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  # pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  # pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  # pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  # pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  # pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  # pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  # pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  # pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
  # pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  # pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  # pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  # pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  # pod 'React-callinvoker', :path => "../node_modules/react-native/ReactCommon/callinvoker"
  # pod 'React-perflogger', :path => "../node_modules/react-native/ReactCommon/reactperflogger"
  # pod 'React-runtimeexecutor', :path => "../node_modules/react-native/ReactCommon/runtimeexecutor"
  # pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  # pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps' #ADD THIS LINE TO YOUR CODE IF YOU WANT GOOGLEMAPS IN IOS
  # pod 'GooglePlaces'
  pod 'Google-Maps-iOS-Utils'

  # pod 'Permission-Motion', :path => "#{permissions_path}/Motion"
  
  # pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  # pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  # pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'

  # pod 'RNDateTimePicker', :podspec => '../node_modules/@react-native-community/datetimepicker'

  # pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  # pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  # pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  
  #pod 'stripe-react-native', :path => '../node_modules/@stripe/stripe-react-native'
  
  # pod 'RNTextGradientView',
  #   :podspec => "../node_modules/react-native-text-gradient/RNTextGradientView.podspec"
  
#  pod 'react-native-firebase', :path => '../node_modules/react-native-firebase/ios'


  #pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  # pod 'react-native-camera', :path => "../node_modules/react-native-camera"

  # pod 'RNPdfScanner', :path => '../node_modules/react-native-document-scanner'

  # pod '@mauron85_react-native-background-geolocation', :path => '../node_modules/@mauron85/react-native-background-geolocation'

  #pod 'RNReactNativePdfLib', :path => '../node_modules/react-native-pdf-lib'

  pod 'RNFS', :path => '../node_modules/react-native-fs'
    
  # pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
    
  # pod 'lottie-ios', :path => '../node_modules/lottie-ios'
    
  # pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
    
  # pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  
  # pod 'react-native-background-downloader', :path => '../node_modules/react-native-background-downloader'

#  pod 'react-native-progress-bar-android', :path => '../node_modules/@react-native-community/progress-bar-android'
#
#  pod 'react-native-progress-view', :path => '../node_modules/@react-native-community/progress-view'

  # pod 'RNSound', :path => '../node_modules/react-native-sound'

  # pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'xeniaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
      installer.pod_targets.each do |pod|
          if $static_framework.include?(pod.name)
            def pod.build_type;
            Pod::BuildType.static_library # >= 1.9
          end
        end
      end
  end
  
  post_install do |installer|
    # `sed -i -e  $'s/__IPHONE_10_0/__IPHONE_12_0/' Pods/RCT-Folly/folly/portability/Time.h`
    # react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      # target.build_configurations.each do |config|
      #   config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      # end
      # if target.name == 'RCT-Folly'
      #   target.build_configurations.each do |config|
      #     config.build_settings['HEADER_SEARCH_PATHS'] = "$(inherited) ${PODS_ROOT}/fmt/include"
      #   end
      # end
    end
    # __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
